- name: Install and configure NTP
  hosts: servers
  become: yes
  tasks:
    - name: Ensure NTP is installed
      apt:
        name: ntp
        state: present

    - name: Ensure NTP is running and enabled
      service:
        name: ntp
        state: started
        enabled: yes
